image: continuumio/miniconda3:latest

stages:
  - test
  - deploy

before_script:
  - pip install pytest
  - pip install pytest-cov
  - pip install twine
  - pip install pyflakes
  - pip install mypy

test_merge_requests:
  stage: test
  script:
    - conda create -n gitlab_test python=3.7
    - source activate gitlab_test
    - conda install gxx_linux-64
    - pip install pytest 
    - pip install pytest-cov
    - pip install pyflakes
    - pip install mypy
    - python setup.py install
    - pytest --cov=probatus/binning --cov=probatus/metric_volatility --cov=probatus/samples --cov=probatus/stat_tests --cov=probatus/utils --cov-report term-missing  --ignore=tests/interpret    - pyflakes probatus
    - mypy probatus --ignore-missing-imports
  only:
  - merge_requests
  - master
  except:
    - tags

deploy_production:
  stage: deploy
  variables:
    TWINE_USERNAME: $PRODUCTION_USERNAME
    TWINE_PASSWORD: $PRODUCTION_PASSWORD
  script:
    - python setup.py sdist
    - twine upload dist/*
  only:
    - tags
